name: Verify PR

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write


on:
  pull_request:
  merge_group:

jobs:
  build:
    name: 🧪 Verify PR
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 📝 Set up node
        uses: meza/action-setup-node-pnpm@71aff4165b6066ca9cc0748cb0859786b78bf35f # main
        with:
          install: true

      - name: 🔬 Lint
        run: pnpm lint:ci

