name: Verify PR

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write


on:
  pull_request:
  merge_group:

jobs:
  build:
    name: 🧪 Verify PR
    runs-on: meza-ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 📝 Set up node
        uses: meza/action-setup-node-pnpm@a2f4240b2835ddfaeb13b353e996e93832b5f47c # main
        with:
          install: true

      - name: 🔬 Lint
        run: pnpm lint:ci

