name: Release

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🚢 Deploy
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: 📝 Set up node
        uses: meza/action-setup-node-pnpm@a2f4240b2835ddfaeb13b353e996e93832b5f47c # main
        with:
          install: true

      - name: 🔬 Lint
        run: pnpm lint

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@b12c8f6015dc215fe37bc154d4ad456dd3833c90 # v6.0.0
        id: semantic-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
